### ISSUE TITLE
t3 app launch app参数格式问题

### ISSUE THREAD

**Issue by PixelMatrixer** [codeskyblue/tidevice3#5]
启动app带入参数时， 写法比较奇怪，需要这样写：
t3 app launch "com.xx.app xx://myprofile"
是否可以改成：
t3 app launch com.xx.app xx://myprofile

需要改下@click.argument("arguments", type=click.STRING)
改成@click.argument("arguments", nargs=-1)

**Comment by codeskyblue** [comment]
这么操作是因为如果这里面包含 -- -之类的字符，会被click当做指令直接给解析了

**Comment by codeskyblue** [comment]
而且后面还可能需要增加环境变量的传递
